//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvdw.helpmij.user {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class HMUserData : global::System.Configuration.ApplicationSettingsBase {
        
        private static HMUserData defaultInstance = ((HMUserData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HMUserData())));
        
        public static HMUserData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.helpmij.nl/")]
        public string siteURL {
            get {
                return ((string)(this["siteURL"]));
            }
            set {
                this["siteURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("forum/login.php")]
        public string loginPHP {
            get {
                return ((string)(this["loginPHP"]));
            }
            set {
                this["loginPHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("do=emailpassword&email=")]
        public string sendPassword {
            get {
                return ((string)(this["sendPassword"]));
            }
            set {
                this["sendPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<span class=\"usertitle\">")]
        public string userstatusPrefix {
            get {
                return ((string)(this["userstatusPrefix"]));
            }
            set {
                this["userstatusPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/forum/member.php/")]
        public string publicprofilePHP {
            get {
                return ((string)(this["publicprofilePHP"]));
            }
            set {
                this["publicprofilePHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<dt>Totaal aantal berichten</dt>\r\n\t\t<dd> ")]
        public string totalPostsPrefix {
            get {
                return ((string)(this["totalPostsPrefix"]));
            }
            set {
                this["totalPostsPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Berichten per dag</dt>\r\n\t\t<dd> ")]
        public string postdayPrefix {
            get {
                return ((string)(this["postdayPrefix"]));
            }
            set {
                this["postdayPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Geregistreerd</dt>\r\n\t\t<dd>  ")]
        public string registeredPrefix {
            get {
                return ((string)(this["registeredPrefix"]));
            }
            set {
                this["registeredPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Laatste activiteit</dt>\r\n\t\t<dd> ")]
        public string lastactivityPrefix {
            get {
                return ((string)(this["lastactivityPrefix"]));
            }
            set {
                this["lastactivityPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</dd>")]
        public string lastactivitySuffix {
            get {
                return ((string)(this["lastactivitySuffix"]));
            }
            set {
                this["lastactivitySuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<title>Bekijk Profiel: ")]
        public string publicuserPrefix {
            get {
                return ((string)(this["publicuserPrefix"]));
            }
            set {
                this["publicuserPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/forum/systemspecs.php?actie=add")]
        public string privateSystemAddPHP {
            get {
                return ((string)(this["privateSystemAddPHP"]));
            }
            set {
                this["privateSystemAddPHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</span>\r\n")]
        public string userstatusSuffix {
            get {
                return ((string)(this["userstatusSuffix"]));
            }
            set {
                this["userstatusSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</dd>\r\n")]
        public string totalPostsSuffix {
            get {
                return ((string)(this["totalPostsSuffix"]));
            }
            set {
                this["totalPostsSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</dd>\r\n")]
        public string postdaySuffix {
            get {
                return ((string)(this["postdaySuffix"]));
            }
            set {
                this["postdaySuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</dd>\r\n")]
        public string registeredSuffix {
            get {
                return ((string)(this["registeredSuffix"]));
            }
            set {
                this["registeredSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" - Helpmij.nl Forum</title>\r\n")]
        public string publicuserSuffix {
            get {
                return ((string)(this["publicuserSuffix"]));
            }
            set {
                this["publicuserSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/forum/image.php?u=")]
        public string avatarUrlPrefix {
            get {
                return ((string)(this["avatarUrlPrefix"]));
            }
            set {
                this["avatarUrlPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("do=finduser&contenttype=vBForum_Post&showposts=1&userid=")]
        public string searchPostsArgs {
            get {
                return ((string)(this["searchPostsArgs"]));
            }
            set {
                this["searchPostsArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/forum/search.php")]
        public string searchPHP {
            get {
                return ((string)(this["searchPHP"]));
            }
            set {
                this["searchPHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("do=finduser&starteronly=1&contenttype=vBForum_Thread&userid=")]
        public string searchPostsStartArgs {
            get {
                return ((string)(this["searchPostsStartArgs"]));
            }
            set {
                this["searchPostsStartArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<a class=\"title\" href=\"")]
        public string searchTopicUrlPrefix {
            get {
                return ((string)(this["searchTopicUrlPrefix"]));
            }
            set {
                this["searchTopicUrlPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\" id=\"thread_title_")]
        public string searchTopicUrlSuffix {
            get {
                return ((string)(this["searchTopicUrlSuffix"]));
            }
            set {
                this["searchTopicUrlSuffix"] = value;
            }
        }
    }
}
