//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvdw.helpmij.forum {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class HMForumData : global::System.Configuration.ApplicationSettingsBase {
        
        private static HMForumData defaultInstance = ((HMForumData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HMForumData())));
        
        public static HMForumData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"/page\"")]
        public string pagePrefix {
            get {
                return ((string)(this["pagePrefix"]));
            }
            set {
                this["pagePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\" href=\"\"member.php/\"")]
        public string memberPrefix {
            get {
                return ((string)(this["memberPrefix"]));
            }
            set {
                this["memberPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"\"\" title=\"")]
        public string memberSuffix {
            get {
                return ((string)(this["memberSuffix"]));
            }
            set {
                this["memberSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"?s=\"")]
        public string authorSuffix {
            get {
                return ((string)(this["authorSuffix"]));
            }
            set {
                this["authorSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"<title> \"")]
        public string titlePrefix {
            get {
                return ((string)(this["titlePrefix"]));
            }
            set {
                this["titlePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"</title>\"")]
        public string titleSuffix {
            get {
                return ((string)(this["titleSuffix"]));
            }
            set {
                this["titleSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"<meta name=\"\"keywords\"\" content=\"\"\"")]
        public string metaKeywordPrefix {
            get {
                return ((string)(this["metaKeywordPrefix"]));
            }
            set {
                this["metaKeywordPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" @\"\"\" />\"")]
        public string metaKeywordSuffix {
            get {
                return ((string)(this["metaKeywordSuffix"]));
            }
            set {
                this["metaKeywordSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"<blockquote class=\"\"postcontent restore \"\">\"")]
        public string commentBodyPrefix {
            get {
                return ((string)(this["commentBodyPrefix"]));
            }
            set {
                this["commentBodyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@\"</blockquote>\"")]
        public string commentBodySuffix {
            get {
                return ((string)(this["commentBodySuffix"]));
            }
            set {
                this["commentBodySuffix"] = value;
            }
        }
    }
}
