//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvdw.helpmij.forum {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class HMForumData : global::System.Configuration.ApplicationSettingsBase {
        
        private static HMForumData defaultInstance = ((HMForumData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HMForumData())));
        
        public static HMForumData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/page")]
        public string pagePrefix {
            get {
                return ((string)(this["pagePrefix"]));
            }
            set {
                this["pagePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" href=\"member.php/")]
        public string memberPrefix {
            get {
                return ((string)(this["memberPrefix"]));
            }
            set {
                this["memberPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\" title=")]
        public string memberSuffix {
            get {
                return ((string)(this["memberSuffix"]));
            }
            set {
                this["memberSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?s=")]
        public string authorSuffix {
            get {
                return ((string)(this["authorSuffix"]));
            }
            set {
                this["authorSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<title> ")]
        public string titlePrefix {
            get {
                return ((string)(this["titlePrefix"]));
            }
            set {
                this["titlePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</title>")]
        public string titleSuffix {
            get {
                return ((string)(this["titleSuffix"]));
            }
            set {
                this["titleSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<meta name=\"keywords\" content=\"")]
        public string metaKeywordPrefix {
            get {
                return ((string)(this["metaKeywordPrefix"]));
            }
            set {
                this["metaKeywordPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\" />")]
        public string metaKeywordSuffix {
            get {
                return ((string)(this["metaKeywordSuffix"]));
            }
            set {
                this["metaKeywordSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<blockquote class=\"postcontent restore \">")]
        public string commentBodyPrefix {
            get {
                return ((string)(this["commentBodyPrefix"]));
            }
            set {
                this["commentBodyPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</blockquote>")]
        public string commentBodySuffix {
            get {
                return ((string)(this["commentBodySuffix"]));
            }
            set {
                this["commentBodySuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.helpmij.nl")]
        public string siteURL {
            get {
                return ((string)(this["siteURL"]));
            }
            set {
                this["siteURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<a href=\"")]
        public string newTopicUrlPrefix {
            get {
                return ((string)(this["newTopicUrlPrefix"]));
            }
            set {
                this["newTopicUrlPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\" class=\"last_title")]
        public string newTopicUrlSuffix {
            get {
                return ((string)(this["newTopicUrlSuffix"]));
            }
            set {
                this["newTopicUrlSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("class=\"last_title\" title=\"")]
        public string newTopicTitlePrefix {
            get {
                return ((string)(this["newTopicTitlePrefix"]));
            }
            set {
                this["newTopicTitlePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"><span>")]
        public string newTopicTitleSuffix {
            get {
                return ((string)(this["newTopicTitleSuffix"]));
            }
            set {
                this["newTopicTitleSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"><span>")]
        public string newTopicTimePrefix {
            get {
                return ((string)(this["newTopicTimePrefix"]));
            }
            set {
                this["newTopicTimePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" &gt;")]
        public string newTopicTimeSuffix {
            get {
                return ((string)(this["newTopicTimeSuffix"]));
            }
            set {
                this["newTopicTimeSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ui-tabs-panel\" id=\"tab_latest_questions_1")]
        public string homepageTab1 {
            get {
                return ((string)(this["homepageTab1"]));
            }
            set {
                this["homepageTab1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ui-tabs-panel\" id=\"tab_latest_questions_2")]
        public string homepageTab2 {
            get {
                return ((string)(this["homepageTab2"]));
            }
            set {
                this["homepageTab2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ui-tabs-panel\" id=\"tab_latest_questions_3")]
        public string homepageTab3 {
            get {
                return ((string)(this["homepageTab3"]));
            }
            set {
                this["homepageTab3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<!-- End tab containers -->")]
        public string hompageTabEnd {
            get {
                return ((string)(this["hompageTabEnd"]));
            }
            set {
                this["hompageTabEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<!-- BEGIN TEMPLATE: footer -->")]
        public string endTopic {
            get {
                return ((string)(this["endTopic"]));
            }
            set {
                this["endTopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<!-- BEGIN TEMPLATE: header -->")]
        public string beginTopic {
            get {
                return ((string)(this["beginTopic"]));
            }
            set {
                this["beginTopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("id=\"yui-gen82\">Pagina 1 van ")]
        public string topicPagesPrefix {
            get {
                return ((string)(this["topicPagesPrefix"]));
            }
            set {
                this["topicPagesPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</a>")]
        public string topicPagesSuffix {
            get {
                return ((string)(this["topicPagesSuffix"]));
            }
            set {
                this["topicPagesSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("?styleid=20")]
        public string mobileStyle {
            get {
                return ((string)(this["mobileStyle"]));
            }
            set {
                this["mobileStyle"] = value;
            }
        }
    }
}
