//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvdw.helpmijapi.artwork.userbar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resUserbars {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resUserbars() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mvdw.helpmijapi.artwork.userbar.resUserbars", typeof(resUserbars).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [USERBAR]
        ///Name=Helpmij Belg Style
        ///Image=UB_Belg_img.png
        ///Preview=UB_Belg_PREVIEW.png
        ///Color_INSIDE_Red=255
        ///Color_INSIDE_Green=255
        ///Color_INSIDE_Blue=255
        ///Color_OUTSIDE_Red=7
        ///Color_OUTSIDE_Green=69
        ///Color_OUTSIDE_Blue=136
        ///Txt_Xpos=335
        ///Txt_Ypos=5.
        /// </summary>
        internal static string UB_Belg {
            get {
                return ResourceManager.GetString("UB_Belg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_Belg_img {
            get {
                object obj = ResourceManager.GetObject("UB_Belg_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_Belg_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("UB_Belg_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [USERBAR]
        ///Name=Helpmij Classic Style
        ///Image=UB_Classic_img.png
        ///Preview=UB_Classic_PREVIEW.png
        ///Color_INSIDE_Red=255
        ///Color_INSIDE_Green=255
        ///Color_INSIDE_Blue=255
        ///Color_OUTSIDE_Red=0
        ///Color_OUTSIDE_Green=0
        ///Color_OUTSIDE_Blue=0
        ///Txt_Xpos=322
        ///Txt_Ypos=5.
        /// </summary>
        internal static string UB_Classic {
            get {
                return ResourceManager.GetString("UB_Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_Classic_img {
            get {
                object obj = ResourceManager.GetObject("UB_Classic_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_Classic_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("UB_Classic_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [USERBAR]
        ///Name=Helpmij Classic Dark Style
        ///Image=UB_ClassicDark_img.png
        ///Preview=UB_ClassicDark_PREVIEW.png
        ///Color_INSIDE_Red=255
        ///Color_INSIDE_Green=255
        ///Color_INSIDE_Blue=255
        ///Color_OUTSIDE_Red=5
        ///Color_OUTSIDE_Green=46
        ///Color_OUTSIDE_Blue=86
        ///Txt_Xpos=334
        ///Txt_Ypos=5.
        /// </summary>
        internal static string UB_ClassicDark {
            get {
                return ResourceManager.GetString("UB_ClassicDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_ClassicDark_img {
            get {
                object obj = ResourceManager.GetObject("UB_ClassicDark_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_ClassicDark_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("UB_ClassicDark_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [USERBAR]
        ///Name=Helpmij Emboss Style
        ///Image=UB_Emboss_img.png
        ///Preview=UB_Emboss.png
        ///Color_INSIDE_Red=255
        ///Color_INSIDE_Green=255
        ///Color_INSIDE_Blue=255
        ///Color_OUTSIDE_Red=0
        ///Color_OUTSIDE_Green=0
        ///Color_OUTSIDE_Blue=0
        ///Txt_Xpos=322
        ///Txt_Ypos=5.
        /// </summary>
        internal static string UB_Emboss {
            get {
                return ResourceManager.GetString("UB_Emboss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_Emboss_img {
            get {
                object obj = ResourceManager.GetObject("UB_Emboss_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_Emboss_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("UB_Emboss_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [USERBAR]
        ///Name=Helpmij Green Spring
        ///Image=UB_GreenSpring_img.png
        ///Preview=UB_GreenSpring_PREVIEW.png
        ///Color_INSIDE_Red=255
        ///Color_INSIDE_Green=255
        ///Color_INSIDE_Blue=255
        ///Color_OUTSIDE_Red=53
        ///Color_OUTSIDE_Green=85
        ///Color_OUTSIDE_Blue=5
        ///Txt_Xpos=332
        ///Txt_Ypos=5.
        /// </summary>
        internal static string UB_GreenSpring {
            get {
                return ResourceManager.GetString("UB_GreenSpring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_GreenSpring_img {
            get {
                object obj = ResourceManager.GetObject("UB_GreenSpring_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_GreenSpring_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("UB_GreenSpring_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [USERBAR]
        ///Name=Helpmij Herfst Style
        ///Image=UB_Herfst_img.png
        ///Preview=UB_Herfst_PREVIEW.png
        ///Color_INSIDE_Red=255
        ///Color_INSIDE_Green=217
        ///Color_INSIDE_Blue=156
        ///Color_OUTSIDE_Red=36
        ///Color_OUTSIDE_Green=29
        ///Color_OUTSIDE_Blue=13
        ///Txt_Xpos=337
        ///Txt_Ypos=5.
        /// </summary>
        internal static string UB_Herfst {
            get {
                return ResourceManager.GetString("UB_Herfst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_Herfst_img {
            get {
                object obj = ResourceManager.GetObject("UB_Herfst_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_Herfst_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("UB_Herfst_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [USERBAR]
        ///Name=Helpmij Nederland Style
        ///Image=UB_Nederland_img.png
        ///Preview=UB_Nederland_PREVIEW.png
        ///Color_INSIDE_Red=255
        ///Color_INSIDE_Green=255
        ///Color_INSIDE_Blue=255
        ///Color_OUTSIDE_Red=7
        ///Color_OUTSIDE_Green=69
        ///Color_OUTSIDE_Blue=136
        ///Txt_Xpos=335
        ///Txt_Ypos=5.
        /// </summary>
        internal static string UB_Nederland {
            get {
                return ResourceManager.GetString("UB_Nederland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_Nederland_img {
            get {
                object obj = ResourceManager.GetObject("UB_Nederland_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_Nederland_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("UB_Nederland_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [USERBAR]
        ///Name=Helpmij Rainbow Blue Style
        ///Image=UB_RainbowBlue_img.png
        ///Preview=UB_RainbowBlue_PREVIEW.png
        ///Color_INSIDE_Red=255
        ///Color_INSIDE_Green=255
        ///Color_INSIDE_Blue=255
        ///Color_OUTSIDE_Red=37
        ///Color_OUTSIDE_Green=39
        ///Color_OUTSIDE_Blue=125
        ///Txt_Xpos=336
        ///Txt_Ypos=5.
        /// </summary>
        internal static string UB_RainbowBlue {
            get {
                return ResourceManager.GetString("UB_RainbowBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_RainbowBlue_img {
            get {
                object obj = ResourceManager.GetObject("UB_RainbowBlue_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_RainbowBlue_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("UB_RainbowBlue_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [USERBAR]
        ///Name=Helpmij Rainbow Green Style
        ///Image=UB_RainbowGreen_img.png
        ///Preview=UB_RainbowGreen_PREVIEW.png
        ///Color_INSIDE_Red=255
        ///Color_INSIDE_Green=255
        ///Color_INSIDE_Blue=255
        ///Color_OUTSIDE_Red=62
        ///Color_OUTSIDE_Green=136
        ///Color_OUTSIDE_Blue=15
        ///Txt_Xpos=336
        ///Txt_Ypos=5.
        /// </summary>
        internal static string UB_RainbowGreen {
            get {
                return ResourceManager.GetString("UB_RainbowGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_RainbowGreen_img {
            get {
                object obj = ResourceManager.GetObject("UB_RainbowGreen_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_RainbowGreen_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("UB_RainbowGreen_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [USERBAR]
        ///Name=Helpmij Rainbow Red Style
        ///Image=UB_RainbowRed_img.png
        ///Preview=UB_RainbowRed_PREVIEW.png
        ///Color_INSIDE_Red=255
        ///Color_INSIDE_Green=255
        ///Color_INSIDE_Blue=255
        ///Color_OUTSIDE_Red=172
        ///Color_OUTSIDE_Green=25
        ///Color_OUTSIDE_Blue=20
        ///Txt_Xpos=336
        ///Txt_Ypos=5.
        /// </summary>
        internal static string UB_RainbowRed {
            get {
                return ResourceManager.GetString("UB_RainbowRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_RainbowRed_img {
            get {
                object obj = ResourceManager.GetObject("UB_RainbowRed_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_RainbowRed_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("UB_RainbowRed_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [USERBAR]
        ///Name=Helpmij Rainbow Yellow Style
        ///Image=UB_RainbowYellow_img.png
        ///Preview=UB_RainbowYellow_PREVIEW.png
        ///Color_INSIDE_Red=255
        ///Color_INSIDE_Green=255
        ///Color_INSIDE_Blue=255
        ///Color_OUTSIDE_Red=114
        ///Color_OUTSIDE_Green=113
        ///Color_OUTSIDE_Blue=28
        ///Txt_Xpos=336
        ///Txt_Ypos=5.
        /// </summary>
        internal static string UB_RainbowYellow {
            get {
                return ResourceManager.GetString("UB_RainbowYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_RainbowYellow_img {
            get {
                object obj = ResourceManager.GetObject("UB_RainbowYellow_img", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UB_RainbowYellow_PREVIEW {
            get {
                object obj = ResourceManager.GetObject("UB_RainbowYellow_PREVIEW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
