//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvdw.helpmij.gebruiker {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class HMGebruikerData : global::System.Configuration.ApplicationSettingsBase {
        
        private static HMGebruikerData defaultInstance = ((HMGebruikerData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HMGebruikerData())));
        
        public static HMGebruikerData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.helpmij.nl/")]
        public string siteURL {
            get {
                return ((string)(this["siteURL"]));
            }
            set {
                this["siteURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("forum/login.php")]
        public string loginPHP {
            get {
                return ((string)(this["loginPHP"]));
            }
            set {
                this["loginPHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("do=emailpassword&email=")]
        public string sendPassword {
            get {
                return ((string)(this["sendPassword"]));
            }
            set {
                this["sendPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<span class=\"usertitle\">")]
        public string userstatusPrefix {
            get {
                return ((string)(this["userstatusPrefix"]));
            }
            set {
                this["userstatusPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</span>\r")]
        public string userstatusSuffix {
            get {
                return ((string)(this["userstatusSuffix"]));
            }
            set {
                this["userstatusSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/forum/member.php/")]
        public string publicprofilePHP {
            get {
                return ((string)(this["publicprofilePHP"]));
            }
            set {
                this["publicprofilePHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<dt>Totaal aantal berichten</dt>\r\n\t\t<dd> ")]
        public string totalPostsPrefix {
            get {
                return ((string)(this["totalPostsPrefix"]));
            }
            set {
                this["totalPostsPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</dd>\r")]
        public string totalPostsSuffix {
            get {
                return ((string)(this["totalPostsSuffix"]));
            }
            set {
                this["totalPostsSuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Berichten per dag</dt>\r\n\t\t<dd> ")]
        public string postdayPrefix {
            get {
                return ((string)(this["postdayPrefix"]));
            }
            set {
                this["postdayPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</dd>\r")]
        public string postdaySuffix {
            get {
                return ((string)(this["postdaySuffix"]));
            }
            set {
                this["postdaySuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Geregistreerd</dt>\r\n\t\t<dd>  ")]
        public string registeredPrefix {
            get {
                return ((string)(this["registeredPrefix"]));
            }
            set {
                this["registeredPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</dd>\r")]
        public string registeredSuffix {
            get {
                return ((string)(this["registeredSuffix"]));
            }
            set {
                this["registeredSuffix"] = value;
            }
        }
    }
}
