//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvdw.helpmij.gebruiker {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class HMGebruikerData : global::System.Configuration.ApplicationSettingsBase {
        
        private static HMGebruikerData defaultInstance = ((HMGebruikerData)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HMGebruikerData())));
        
        public static HMGebruikerData Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.helpmij.nl/")]
        public string siteURL {
            get {
                return ((string)(this["siteURL"]));
            }
            set {
                this["siteURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("forum/login.php")]
        public string loginPHP {
            get {
                return ((string)(this["loginPHP"]));
            }
            set {
                this["loginPHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("do=emailpassword&email=")]
        public string sendPassword {
            get {
                return ((string)(this["sendPassword"]));
            }
            set {
                this["sendPassword"] = value;
            }
        }
    }
}
